import streamlit as st
import pandas as pd
from helpers import is_history, CONVERSATION_HISTORY, clean_history

st.set_page_config(
    page_title="Documentation",
    page_icon="📜",
)


w = """
## How does the Compliance Oracle function?


**Objective of the applicaton**

The Compliance Oracle assists actuaries in enhancing their compliance knowledge and expertise. Leveraging documents and guidelines from the Monetary Authority of Singapore (MAS), this innovative tool employs advanced natural language processing and machine learning algorithms to analyze and synthesize complex regulatory information. By doing so, it creates intuitive, easily digestible summaries and insights that help actuaries stay abreast of the latest compliance requirements and industry standards.

**Disclaimer**

Please note that this app serves as a tool for research and development purposes only. Users are advised to exercise their professional judgment, as there is no guarantee of the accuracy or reliability of the information provided.


**How to give Feedback?**

- Join us here: https://chat.whatsapp.com/KKVKUCPLgp763iiTXVs3Du
- Click thumbs and down on the chat! (Only works the first time)

**Technical Considerations**
1. LLM used: GPT 3.5 turbo
2. Embedding model: intfloat/multilingual-e5-base
3. Vector Database: FAISS


**Safety considerations**
1. A Guard model will first validate whether the prompt is related to an Insurance question.
2. The Compliance Oracle will give the citations of the document that he found relevant to your question.
3. The compliance oracle will give a confidence score related to how likely he was able to find a document related to your questions.

**MAS Document used**
| Document                                                     | URL                                                                                                                                                                                                                                                                                                                                                                                                                                      | Date Accessed |
| ------------------------------------------------------------ | ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ------------- |
| SAS SAP L01_0.pdf                                            | [https://www.actuaries.org.sg/documents/l01](https://www.actuaries.org.sg/documents/l01)                                                                                                                                                                                                                                                                                                                                                 | 26/1/2024     |
| SAS SAP L02_0.pdf                                            | [https://www.actuaries.org.sg/documents/l02](https://www.actuaries.org.sg/documents/l02)                                                                                                                                                                                                                                                                                                                                                 | 26/1/2024     |
| SAS-SAP-X01-Effective-01Jan18.pdf                            | [https://www.actuaries.org.sg/documents/x01](https://www.actuaries.org.sg/documents/x01)                                                                                                                                                                                                                                                                                                                                                 | 26/1/2024     |
| SAS-SAP-G01-Effective-01Jan18.pdf                            | [https://www.actuaries.org.sg/documents/g01](https://www.actuaries.org.sg/documents/g01)                                                                                                                                                                                                                                                                                                                                                 | 26/1/2024     |
| SAS-SAP-L03-Effective-01Jan18.pdf                            | [https://www.actuaries.org.sg/documents/l03](https://www.actuaries.org.sg/documents/l03)                                                                                                                                                                                                                                                                                                                                                 | 26/1/2024     |
| SAS-SAP-Glossary-Effective01Jan18.pdf                        | [https://www.actuaries.org.sg/documents/glossary](https://www.actuaries.org.sg/documents/glossary)                                                                                                                                                                                                                                                                                                                                       | 26/1/2024     |
| Notice 122_301123.pdf                                        | [https://www.mas.gov.sg/-/media/mas-media-library/regulation/notices/id/notice-122/notice-122_301123.pdf](https://www.mas.gov.sg/-/media/mas-media-library/regulation/notices/id/notice-122/notice-122_301123.pdf)                                                                                                                                                                                                                       | 26/1/2024     |
| Insurance Act 1966.pdf                                       | [https://sso.agc.gov.sg/Act/IA1966](https://sso.agc.gov.sg/Act/IA1966)                                                                                                                                                                                                                                                                                                                                                                   | 27/1/2024     |
| Insurance (Actuaries) Regulations 2013.pdf                   | [https://sso.agc.gov.sg/SL-Supp/S239-2013/Published/20130417?DocDate=20130417](https://sso.agc.gov.sg/SL-Supp/S239-2013/Published/20130417?DocDate=20130417)                                                                                                                                                                                                                                                                             | 27/1/2024     |
| Deposit Insurance and Policy Owners’ Protection Sc.pdf       | [https://sso.agc.gov.sg/Act/DIPOPSA2011](https://sso.agc.gov.sg/Act/DIPOPSA2011)                                                                                                                                                                                                                                                                                                                                                         | 27/1/2024     |
| Financial Advisers Regulations.pdf                           | [https://sso.agc.gov.sg/SL/FAA2001-RG2](https://sso.agc.gov.sg/SL/FAA2001-RG2)                                                                                                                                                                                                                                                                                                                                                           | 27/1/2024     |
| Financial Advisers Act 2001.pdf                              | [https://sso.agc.gov.sg/Act/FAA2001](https://sso.agc.gov.sg/Act/FAA2001)                                                                                                                                                                                                                                                                                                                                                                 | 27/1/2024     |
| Financial Advisers (Remuneration) Regulations 2015.pdf       | [https://sso.agc.gov.sg/SL/FAA2001-S816-2015](https://sso.agc.gov.sg/SL/FAA2001-S816-2015)                                                                                                                                                                                                                                                                                                                                               | 27/1/2024     |
| MAS 322_Amendment_clean_27 Nov 2023.pdf                      | [https://www.mas.gov.sg/-/media/mas-media-library/regulation/notices/id/notice-322/mas-322_amendment_clean_27-nov-2023.pdf](https://www.mas.gov.sg/-/media/mas-media-library/regulation/notices/id/notice-322/mas-322_amendment_clean_27-nov-2023.pdf)                                                                                                                                                                                   | 27/1/2024     |
| MAS 307_clean_28 Jun 2021.pdf                                | [https://www.mas.gov.sg/-/media/mas-media-library/regulation/notices/id/notice-307/mas-307_clean_28-jun-2021.pdf](https://www.mas.gov.sg/-/media/mas-media-library/regulation/notices/id/notice-307/mas-307_clean_28-jun-2021.pdf)                                                                                                                                                                                                       | 27/1/2024     |
| MAS 125_30 Sep 2022.pdf                                      | [https://www.mas.gov.sg/-/media/mas-media-library/regulation/notices/id/notice-125/mas-125_30-sep-2022.pdf](https://www.mas.gov.sg/-/media/mas-media-library/regulation/notices/id/notice-125/mas-125_30-sep-2022.pdf)                                                                                                                                                                                                                   | 27/1/2024     |
| Notice 321 Clean.pdf                                         | [https://www.mas.gov.sg/-/media/mas/regulations-and-financial-stability/regulations-guidance-and-licensing/insurance/regulations-guidance-and-licensing/notices/notices-to-life-insurers/notice-321-clean.pdf](https://www.mas.gov.sg/-/media/mas/regulations-and-financial-stability/regulations-guidance-and-licensing/insurance/regulations-guidance-and-licensing/notices/notices-to-life-insurers/notice-321-clean.pdf)             | 27/1/2024     |
| MAS Notice 133_8 December 2023.pdf                           | [https://www.mas.gov.sg/-/media/mas-media-library/regulation/notices/id/notice-133/mas-notice-133_8-december-2023.pdf](https://www.mas.gov.sg/-/media/mas-media-library/regulation/notices/id/notice-133/mas-notice-133_8-december-2023.pdf)                                                                                                                                                                                             | 27/1/2024     |
| MAS Notice 318 Published Version 2018.pdf                    | [https://www.mas.gov.sg/-/media/mas/notices/pdf/mas-notice-318-published-version-2018.pdf](https://www.mas.gov.sg/-/media/mas/notices/pdf/mas-notice-318-published-version-2018.pdf)                                                                                                                                                                                                                                                     | 27/1/2024     |
| MAS 302 Clean.pdf                                            | [https://www.mas.gov.sg/-/media/mas/regulations-and-financial-stability/regulations-guidance-and-licensing/insurance/regulations-guidance-and-licensing/notices/notices-to-life-insurers/mas-302-clean.pdf](https://www.mas.gov.sg/-/media/mas/regulations-and-financial-stability/regulations-guidance-and-licensing/insurance/regulations-guidance-and-licensing/notices/notices-to-life-insurers/mas-302-clean.pdf)                   | 27/1/2024     |
| 310522 MAS 120_Revised May 2022                              | [https://www.mas.gov.sg/-/media/mas-media-library/regulation/notices/id/notice-120/310522-mas-120_revised-may-2022.pdf](https://www.mas.gov.sg/-/media/mas-media-library/regulation/notices/id/notice-120/310522-mas-120_revised-may-2022.pdf)                                                                                                                                                                                           | 27/1/2024     |
| MAS-114-_Mar-2020_Clean.pdf                                  | [https://www.mas.gov.sg/-/media/mas/regulations-and-financial-stability/regulations-guidance-and-licensing/insurance/regulations-guidance-and-licensing/notices/notices-to-all-insurers/mas-114-_mar-2020_clean.pdf](https://www.mas.gov.sg/-/media/mas/regulations-and-financial-stability/regulations-guidance-and-licensing/insurance/regulations-guidance-and-licensing/notices/notices-to-all-insurers/mas-114-_mar-2020_clean.pdf) | 27/1/2024     |
| mu-2218-lia-guidelines-on-pi-cp-and-bpd-mu2218-sentzip.pdf   | [https://www.lia.org.sg/media/1237/mu-2218-lia-guidelines-on-pi-cp-and-bpd-mu2218-sentzip.pdf](https://www.lia.org.sg/media/1237/mu-2218-lia-guidelines-on-pi-cp-and-bpd-mu2218-sentzip.pdf)                                                                                                                                                                                                                                             | 27/1/2024     |
| mu6615.pdf                                                   | [https://www.lia.org.sg/media/1472/mu6615.docx](https://www.lia.org.sg/media/1472/mu6615.docx)                                                                                                                                                                                                                                                                                                                                           | 27/1/2024     |
| mu7219.pdf                                                   | [https://www.lia.org.sg/media/2084/mu7219.pdf](https://www.lia.org.sg/media/2084/mu7219.pdf)                                                                                                                                                                                                                                                                                                                                             | 27/1/2024     |
| mu-6318-dpi-guidelines.pdf                                   | [https://www.lia.org.sg/media/1482/mu-6318-dpi-guidelines.pdf](https://www.lia.org.sg/media/1482/mu-6318-dpi-guidelines.pdf)                                                                                                                                                                                                                                                                                                             | 27/1/2024     |
| mu7420.pdf                                                   | [https://www.lia.org.sg/media/3062/mu7420.pdf](https://www.lia.org.sg/media/3062/mu7420.pdf)                                                                                                                                                                                                                                                                                                                                             | 27/1/2024     |
| 1 July 2021 FSGG01 Guidelines on Fit and Proper Criteria.pdf | [https://www.mas.gov.sg/-/media/MAS/Regulations-and-Financial-Stability/Regulations-Guidance-and-Licensing/Financial-Advisers/Guidelines/1-July-2021-FSGG01-Guidelines-on-Fit-and-Proper-Criteria.pdf](https://www.mas.gov.sg/-/media/MAS/Regulations-and-Financial-Stability/Regulations-Guidance-and-Licensing/Financial-Advisers/Guidelines/1-July-2021-FSGG01-Guidelines-on-Fit-and-Proper-Criteria.pdf)                             | 18/2/2024     |



"""

st.write(w)



    #if st.button('Clean history'):
    #    clean_history()
    #    history_placeholder.empty()
