API_URL = "https://cfds-ccm-prod.orm.datarobot.com/predApi/v1.0/deployments/{deployment_id}/predictions"
API_KEY = "YOUR API KEY"
DATAROBOT_KEY = "YOUR DATAROBOT KEY"
DR_ENDPOINT = "https://app.datarobot.com/api/v2"
DEFAULT_GUARD_MODEL_DEPLOYMENT_ID = 'YOUR GUARD MODEL ID'
DEFAULT_GENAI_MODEL_DEPLOYMENT_ID = 'YOUR GENAI APPLICATION ID'
