API_URL = "https://cfds-ccm-prod.orm.datarobot.com/predApi/v1.0/deployments/{deployment_id}/predictions"
API_KEY = "YOUR API KEY"
DATAROBOT_KEY = "YOUR DATAROBOT KEY"
DR_ENDPOINT = "https://app.datarobot.com/api/v2"
DEFAULT_GUARD_MODEL_DEPLOYMENT_ID = '658cabe55f6e3e091897d40f'
DEFAULT_GENAI_MODEL_DEPLOYMENT_ID = '658caa9a8556f2c2176dfae7'
